import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Test Campaign - Skill Verification",
  description: "Landing page generated by skill test"
}

export default function Page() {
  return (
    <div style={{padding: "40px", textAlign: "center", fontFamily: "sans-serif"}}>
      <h1>🎉 Test Campaign Live!</h1>
      <p>This page was generated and deployed by the landing page builder skill.</p>
      <div style={{backgroundColor: "#f0f0f0", padding: "20px", borderRadius: "8px", margin: "20px 0"}}>
        <h2>✅ Verification Checks:</h2>
        <ul style={{textAlign: "left", display: "inline-block"}}>
          <li>✓ Page generated correctly</li>
          <li>✓ Files pushed to GitHub</li>
          <li>✓ Campaign registered</li>
          <li>✓ Vercel deployment triggered</li>
          <li>✓ URL is live</li>
          <li>✓ Content is rendering</li>
        </ul>
      </div>
      <p style={{color: "#666"}}>Slug: test-1789436968</p>
    </div>
  )
}